export type NavigationItem = {
  label: string;
  path: string;
  description: string;
  permissionKeys: string[];
  section?: string;
  pageTitle?: string;
  pageDescription?: string;
  driverOnly?: boolean;
  driverScoped?: boolean;
  adminOnly?: boolean;
};

export type SidebarSection = {
  key: string;
  label: string;
  items: NavigationItem[];
};

export const navigationItems: NavigationItem[] = [
  // ─── Driver-only items (always shown to drivers) ───
  {
    label: 'My Dashboard',
    path: '/my-dashboard',
    description: 'Your personal driver dashboard',
    permissionKeys: [],
    section: 'MY',
    pageTitle: 'My Dashboard',
    pageDescription: 'Your personal driver dashboard',
    driverOnly: true,
  },
  {
    label: 'My Trips',
    path: '/my-trips',
    description: 'View your trips and history',
    permissionKeys: [],
    section: 'MY',
    pageTitle: 'My Trips',
    pageDescription: 'Your trip history and active trips',
    driverOnly: true,
  },
  {
    label: 'My Documents',
    path: '/my-documents',
    description: 'View your documents',
    permissionKeys: [],
    section: 'MY',
    pageTitle: 'My Documents',
    pageDescription: 'Your uploaded documents and files',
    driverOnly: true,
  },
  {
    label: 'My Profile',
    path: '/my-profile',
    description: 'View your driver profile',
    permissionKeys: [],
    section: 'MY',
    pageTitle: 'My Profile',
    pageDescription: 'Your driver profile information',
    driverScoped: true,
  },
  // ─── Driver-scoped permission-based items ───
  {
    label: 'Quick Fuel Entry',
    path: '/fuel/new',
    description: 'Add a quick fuel entry',
    permissionKeys: ['driver_quick_fuel_create'],
    section: 'ACTIONS',
    pageTitle: 'Quick Fuel Entry',
    pageDescription: 'Quick fuel entry for your assigned vehicle',
    driverScoped: true,
  },
  {
    label: 'Upload Fuel Bill',
    path: '/fuel/new',
    description: 'Upload a fuel receipt',
    permissionKeys: ['driver_fuel_receipt_upload'],
    section: 'ACTIONS',
    pageTitle: 'Upload Fuel Bill',
    pageDescription: 'Upload fuel bill or receipt',
    driverScoped: true,
  },
  {
    label: 'Expense Claim',
    path: '/expenses/new',
    description: 'Create an expense claim',
    permissionKeys: ['driver_expense_create'],
    section: 'ACTIONS',
    pageTitle: 'Expense Claim',
    pageDescription: 'Submit a trip or vehicle expense',
    driverScoped: true,
  },
  // ─── Admin/Manager items ───
  {
    label: 'Overview',
    path: '/',
    description: 'Current session and permission summary',
    permissionKeys: [],
    section: 'EXPLORE',
    pageTitle: 'Overview',
    pageDescription: 'Identity, permission, and staging status',
  },
  {
    label: 'Activity History',
    path: '/trips',
    description: 'Recent trips and activity',
    permissionKeys: ['trip_view'],
    section: 'EXPLORE',
    pageTitle: 'Activity History',
    pageDescription: 'Recent trips and activity',
  },
  {
    label: 'New Trip',
    path: '/trips/new',
    description: 'Create a new trip',
    permissionKeys: ['trip_create'],
    section: 'BUILD',
    pageTitle: 'New Trip',
    pageDescription: 'Create a new trip',
  },
  {
    label: 'My Fleet',
    path: '/vehicles',
    description: 'Manage your vehicles',
    permissionKeys: ['vehicle_view'],
    section: 'BUILD',
    pageTitle: 'My Fleet',
    pageDescription: 'Manage your vehicles',
  },
  {
    label: 'Asset Library',
    path: '/assets',
    description: 'Browse assets and equipment',
    permissionKeys: ['asset_view'],
    section: 'BUILD',
    pageTitle: 'Asset Library',
    pageDescription: 'Browse assets and equipment',
  },
  {
    label: 'Dashboard',
    path: '/',
    description: 'Fleet overview and quick links',
    permissionKeys: [],
    section: 'MANAGE',
    pageTitle: 'Dashboard',
    pageDescription: 'Fleet overview and quick links',
  },
  {
    label: 'Vehicles',
    path: '/vehicles',
    description: 'Manage vehicle master data',
    permissionKeys: ['vehicle_view'],
    section: 'MANAGE',
    pageTitle: 'Vehicles',
    pageDescription: 'Vehicle master records',
  },
  {
    label: 'Drivers',
    path: '/drivers',
    description: 'Manage driver master data',
    permissionKeys: ['driver_view'],
    section: 'MANAGE',
    pageTitle: 'Drivers',
    pageDescription: 'Driver master records',
  },
  {
    label: 'Assets',
    path: '/assets',
    description: 'Manage inventory and equipment',
    permissionKeys: ['asset_view'],
    section: 'MANAGE',
    pageTitle: 'Assets',
    pageDescription: 'Asset master records',
  },
  {
    label: 'Trips',
    path: '/trips',
    description: 'Manage trips and transfers',
    permissionKeys: ['trip_view'],
    section: 'MANAGE',
    pageTitle: 'Trips',
    pageDescription: 'Trip and transfer workflow',
  },
  {
    label: 'Fuel',
    path: '/fuel',
    description: 'Fuel entries and approvals',
    permissionKeys: ['fuel_view'],
    section: 'MANAGE',
    pageTitle: 'Fuel',
    pageDescription: 'Fuel entry workflow',
  },
  {
    label: 'Expenses',
    path: '/expenses',
    description: 'Vehicle and trip expenses',
    permissionKeys: ['expense_view'],
    section: 'MANAGE',
    pageTitle: 'Expenses',
    pageDescription: 'Expense workflow',
  },
  {
    label: 'Maintenance',
    path: '/maintenance',
    description: 'Maintenance requests and schedules',
    permissionKeys: ['maintenance_view'],
    section: 'MANAGE',
    pageTitle: 'Maintenance',
    pageDescription: 'Maintenance request workflow',
  },
  {
    label: 'Repairs',
    path: '/repairs',
    description: 'Vehicle repair tracking',
    permissionKeys: ['repair_view'],
    section: 'MANAGE',
    pageTitle: 'Repairs',
    pageDescription: 'Repair tracking workflow',
  },
  {
    label: 'Compliance',
    path: '/compliance',
    description: 'India vehicle compliance dashboard',
    permissionKeys: ['vehicle_compliance_view'],
    section: 'MANAGE',
    pageTitle: 'Compliance Dashboard',
    pageDescription: 'Insurance, permits, fitness, PUC, road tax, FASTag, and AIS-140 GPS tracking',
  },
  {
    label: 'Finance',
    path: '/finance',
    description: 'Finance management, P&L, transactions, and billing',
    permissionKeys: [
      'finance_view',
      'pnl_view',
      'finance_transactions_view',
      'vendors_view',
      'customers_view',
      'trip_billing_view',
      'payments_view',
    ],
    section: 'MANAGE',
    pageTitle: 'Finance',
    pageDescription: 'Financial management, P&L, transactions, vendors, customers, billing, and payments',
    adminOnly: true,
  },
  {
    label: 'Documents',
    path: '/documents',
    description: 'Manage fleet documents and files',
    permissionKeys: ['documents_view'],
    section: 'MANAGE',
    pageTitle: 'Documents Vault',
    pageDescription: 'Store and manage fleet documents, compliance files, invoices, proofs, and trip papers',
  },
  {
    label: 'Roles',
    path: '/roles',
    description: 'Roles and permission assignments',
    permissionKeys: ['role_view'],
    section: 'MANAGE',
    pageTitle: 'Roles and permissions',
    pageDescription: 'Role definitions and permission coverage',
    adminOnly: true,
  },
  {
    label: 'Users',
    path: '/users',
    description: 'Create, update, and review user access',
    permissionKeys: ['user_view'],
    section: 'MANAGE',
    pageTitle: 'Users',
    pageDescription: 'User access management',
    adminOnly: true,
  },
];

export const sidebarSections: SidebarSection[] = [
  {
    key: 'MY',
    label: 'MY',
    items: navigationItems.filter((item) => item.section === 'MY'),
  },
  {
    key: 'EXPLORE',
    label: 'EXPLORE',
    items: navigationItems.filter((item) => item.section === 'EXPLORE'),
  },
  {
    key: 'BUILD',
    label: 'BUILD',
    items: navigationItems.filter((item) => item.section === 'BUILD'),
  },
  {
    key: 'MANAGE',
    label: 'MANAGE',
    items: navigationItems.filter((item) => item.section === 'MANAGE'),
  },
];
