type PermissionDefinition = {
  key: string;
  module: string;
  action: string;
  description: string;
};

type RoleDefinition = {
  name: string;
  key: string;
  description: string;
  isSystem: boolean;
  status: 'ACTIVE' | 'INACTIVE';
};

export const permissionDefinitions: PermissionDefinition[] = [
  { key: 'user_view', module: 'users', action: 'view', description: 'View users' },
  { key: 'user_create', module: 'users', action: 'create', description: 'Create users' },
  { key: 'user_update', module: 'users', action: 'update', description: 'Update users' },
  { key: 'user_delete', module: 'users', action: 'delete', description: 'Delete users' },
  { key: 'user_deactivate', module: 'users', action: 'deactivate', description: 'Deactivate users' },
  { key: 'role_view', module: 'roles', action: 'view', description: 'View roles' },
  { key: 'role_create', module: 'roles', action: 'create', description: 'Create roles' },
  { key: 'role_update', module: 'roles', action: 'update', description: 'Update roles' },
  { key: 'role_delete', module: 'roles', action: 'delete', description: 'Delete roles' },
  { key: 'permission_view', module: 'permissions', action: 'view', description: 'View permissions' },
  { key: 'permission_assign', module: 'permissions', action: 'assign', description: 'Assign permissions' },
  { key: 'vehicle_view', module: 'vehicles', action: 'view', description: 'View vehicles' },
  { key: 'vehicle_create', module: 'vehicles', action: 'create', description: 'Create vehicles' },
  { key: 'vehicle_update', module: 'vehicles', action: 'update', description: 'Update vehicles' },
  { key: 'vehicle_delete', module: 'vehicles', action: 'delete', description: 'Delete vehicles' },
  { key: 'driver_view', module: 'drivers', action: 'view', description: 'View drivers' },
  { key: 'driver_create', module: 'drivers', action: 'create', description: 'Create drivers' },
  { key: 'driver_update', module: 'drivers', action: 'update', description: 'Update drivers' },
  { key: 'driver_delete', module: 'drivers', action: 'delete', description: 'Delete drivers' },
  { key: 'asset_view', module: 'assets', action: 'view', description: 'View assets' },
  { key: 'asset_create', module: 'assets', action: 'create', description: 'Create assets' },
  { key: 'asset_update', module: 'assets', action: 'update', description: 'Update assets' },
  { key: 'asset_delete', module: 'assets', action: 'delete', description: 'Delete assets' },
  { key: 'asset_assign', module: 'assets', action: 'assign', description: 'Assign assets' },
  { key: 'asset_return', module: 'assets', action: 'return', description: 'Return assets' },
  { key: 'asset_transfer', module: 'assets', action: 'transfer', description: 'Transfer assets between holders' },
  { key: 'asset_mark_damaged', module: 'assets', action: 'mark_damaged', description: 'Mark assets as damaged' },
  { key: 'asset_mark_lost', module: 'assets', action: 'mark_lost', description: 'Mark assets as lost' },
  { key: 'trip_view', module: 'trips', action: 'view', description: 'View trips' },
  { key: 'trip_create', module: 'trips', action: 'create', description: 'Create trips' },
  { key: 'trip_update', module: 'trips', action: 'update', description: 'Update trips' },
  { key: 'trip_start', module: 'trips', action: 'start', description: 'Start trips' },
  { key: 'trip_end', module: 'trips', action: 'end', description: 'End trips' },
  { key: 'trip_cancel', module: 'trips', action: 'cancel', description: 'Cancel trips' },
  { key: 'fuel_view', module: 'fuel', action: 'view', description: 'View fuel logs' },
  { key: 'fuel_create', module: 'fuel', action: 'create', description: 'Create fuel logs' },
  { key: 'fuel_update', module: 'fuel', action: 'update', description: 'Update fuel logs' },
  { key: 'fuel_delete', module: 'fuel', action: 'delete', description: 'Delete or cancel fuel logs' },
  { key: 'fuel_submit', module: 'fuel', action: 'submit', description: 'Submit fuel logs' },
  { key: 'fuel_approve', module: 'fuel', action: 'approve', description: 'Approve fuel logs' },
  { key: 'expense_view', module: 'expenses', action: 'view', description: 'View expenses' },
  { key: 'expense_create', module: 'expenses', action: 'create', description: 'Create expenses' },
  { key: 'expense_update', module: 'expenses', action: 'update', description: 'Update expenses' },
  { key: 'expense_delete', module: 'expenses', action: 'delete', description: 'Delete or cancel expenses' },
  { key: 'expense_submit', module: 'expenses', action: 'submit', description: 'Submit expenses' },
  { key: 'expense_approve', module: 'expenses', action: 'approve', description: 'Approve expenses' },
  { key: 'repair_view', module: 'repairs', action: 'view', description: 'View repairs' },
  { key: 'repair_create', module: 'repairs', action: 'create', description: 'Create repairs' },
  { key: 'repair_update', module: 'repairs', action: 'update', description: 'Update repairs' },
  { key: 'repair_close', module: 'repairs', action: 'close', description: 'Close repairs' },
  { key: 'maintenance_view', module: 'maintenance', action: 'view', description: 'View maintenance requests' },
  { key: 'maintenance_create', module: 'maintenance', action: 'create', description: 'Create maintenance requests' },
  { key: 'maintenance_update', module: 'maintenance', action: 'update', description: 'Update maintenance requests' },
  { key: 'maintenance_submit', module: 'maintenance', action: 'submit', description: 'Submit maintenance requests' },
  { key: 'maintenance_approve', module: 'maintenance', action: 'approve', description: 'Approve maintenance requests' },
  { key: 'finance_view', module: 'finance', action: 'view', description: 'View finance' },
  { key: 'finance_approve', module: 'finance', action: 'approve', description: 'Approve finance records' },
  { key: 'report_view', module: 'reports', action: 'view', description: 'View reports' },
  { key: 'report_export', module: 'reports', action: 'export', description: 'Export reports' },
  { key: 'settings_view', module: 'settings', action: 'view', description: 'View settings' },
  { key: 'settings_update', module: 'settings', action: 'update', description: 'Update settings' },
  { key: 'vehicle_compliance_view', module: 'vehicle_compliance', action: 'view', description: 'View vehicle compliance records' },
  { key: 'vehicle_compliance_create', module: 'vehicle_compliance', action: 'create', description: 'Create vehicle compliance records' },
  { key: 'vehicle_compliance_update', module: 'vehicle_compliance', action: 'update', description: 'Update vehicle compliance records' },
  { key: 'vehicle_compliance_delete', module: 'vehicle_compliance', action: 'delete', description: 'Delete vehicle compliance records' },
  { key: 'vehicle_compliance_verify', module: 'vehicle_compliance', action: 'verify', description: 'Verify vehicle compliance documents' },
  { key: 'vehicle_compliance_renew', module: 'vehicle_compliance', action: 'renew', description: 'Renew vehicle compliance records' },
  { key: 'document_metadata_view', module: 'document_metadata', action: 'view', description: 'View document metadata' },
  { key: 'document_metadata_create', module: 'document_metadata', action: 'create', description: 'Create document metadata' },
  { key: 'document_metadata_update', module: 'document_metadata', action: 'update', description: 'Update document metadata' },
  { key: 'document_metadata_delete', module: 'document_metadata', action: 'delete', description: 'Delete document metadata' },
  { key: 'document_metadata_verify', module: 'document_metadata', action: 'verify', description: 'Verify document metadata' },
  { key: 'documents_view', module: 'documents', action: 'view', description: 'View documents' },
  { key: 'documents_upload', module: 'documents', action: 'upload', description: 'Upload documents' },
  { key: 'documents_download', module: 'documents', action: 'download', description: 'Download documents' },
  { key: 'documents_update', module: 'documents', action: 'update', description: 'Update document metadata' },
  { key: 'documents_delete', module: 'documents', action: 'delete', description: 'Delete documents' },
  { key: 'documents_verify', module: 'documents', action: 'verify', description: 'Verify documents' },
  { key: 'documents_archive', module: 'documents', action: 'archive', description: 'Archive documents' },
  { key: 'compliance_alerts_view', module: 'compliance_alerts', action: 'view', description: 'View compliance alerts' },
  { key: 'compliance_history_view', module: 'compliance_history', action: 'view', description: 'View compliance history' },
  { key: 'finance_create', module: 'finance', action: 'create', description: 'Create finance records' },
  { key: 'finance_update', module: 'finance', action: 'update', description: 'Update finance records' },
  { key: 'finance_delete', module: 'finance', action: 'delete', description: 'Delete finance records' },
  { key: 'finance_transactions_view', module: 'finance_transactions', action: 'view', description: 'View finance transactions' },
  { key: 'finance_transactions_create', module: 'finance_transactions', action: 'create', description: 'Create finance transactions' },
  { key: 'finance_transactions_update', module: 'finance_transactions', action: 'update', description: 'Update finance transactions' },
  { key: 'finance_transactions_delete', module: 'finance_transactions', action: 'delete', description: 'Delete finance transactions' },
  { key: 'trip_billing_view', module: 'trip_billing', action: 'view', description: 'View trip billing' },
  { key: 'trip_billing_create', module: 'trip_billing', action: 'create', description: 'Create trip billing' },
  { key: 'trip_billing_update', module: 'trip_billing', action: 'update', description: 'Update trip billing' },
  { key: 'trip_billing_delete', module: 'trip_billing', action: 'delete', description: 'Delete trip billing' },
  { key: 'trip_billing_mark_paid', module: 'trip_billing', action: 'mark_paid', description: 'Mark trip billing as paid' },
  { key: 'payments_view', module: 'payments', action: 'view', description: 'View payments' },
  { key: 'payments_create', module: 'payments', action: 'create', description: 'Create payments' },
  { key: 'payments_update', module: 'payments', action: 'update', description: 'Update payments' },
  { key: 'payments_delete', module: 'payments', action: 'delete', description: 'Delete payments' },
  { key: 'vendors_view', module: 'vendors', action: 'view', description: 'View vendors' },
  { key: 'vendors_create', module: 'vendors', action: 'create', description: 'Create vendors' },
  { key: 'vendors_update', module: 'vendors', action: 'update', description: 'Update vendors' },
  { key: 'vendors_delete', module: 'vendors', action: 'delete', description: 'Delete vendors' },
  { key: 'customers_view', module: 'customers', action: 'view', description: 'View customers' },
  { key: 'customers_create', module: 'customers', action: 'create', description: 'Create customers' },
  { key: 'customers_update', module: 'customers', action: 'update', description: 'Update customers' },
  { key: 'customers_delete', module: 'customers', action: 'delete', description: 'Delete customers' },
  { key: 'pnl_view', module: 'pnl', action: 'view', description: 'View P&L reports' },
  { key: 'finance_history_view', module: 'finance_history', action: 'view', description: 'View finance history' },
  { key: 'alerts_view', module: 'alerts', action: 'view', description: 'View alerts and notifications' },
  { key: 'alerts_manage', module: 'alerts', action: 'manage', description: 'Trigger alert generation and edit alert rules' },
  { key: 'alerts_resolve', module: 'alerts', action: 'resolve', description: 'Read, resolve, and dismiss alerts' },
];

export const roleDefinitions: RoleDefinition[] = [
  { name: 'Super Admin', key: 'super_admin', description: 'Full platform control', isSystem: true, status: 'ACTIVE' },
  { name: 'Admin', key: 'admin', description: 'Company administration', isSystem: true, status: 'ACTIVE' },
  { name: 'Manager', key: 'manager', description: 'Operations manager', isSystem: true, status: 'ACTIVE' },
  { name: 'Supervisor', key: 'supervisor', description: 'Field supervisor', isSystem: true, status: 'ACTIVE' },
  { name: 'Driver', key: 'driver', description: 'Assigned driver', isSystem: true, status: 'ACTIVE' },
  { name: 'Assistant Driver', key: 'assistant_driver', description: 'Assistant driver', isSystem: true, status: 'ACTIVE' },
  { name: 'Collector', key: 'collector', description: 'Collection operator', isSystem: true, status: 'ACTIVE' },
  { name: 'Mechanic', key: 'mechanic', description: 'Repair operator', isSystem: true, status: 'ACTIVE' },
  { name: 'Finance', key: 'finance', description: 'Finance approver', isSystem: true, status: 'ACTIVE' },
  { name: 'Viewer', key: 'viewer', description: 'Read-only operator', isSystem: true, status: 'ACTIVE' },
];

export const criticalSuperAdminPermissionKeys = [
  'role_view',
  'role_update',
  'permission_view',
  'permission_assign',
  'user_view',
  'user_create',
  'user_update',
];

export const criticalRoleManagementPermissionKeys = [
  'role_view',
  'role_update',
  'permission_view',
  'permission_assign',
];

const allPermissionKeys = permissionDefinitions.map((permission) => permission.key);
const viewOnlyPermissionKeys = permissionDefinitions
  .filter((permission) => permission.action === 'view')
  .map((permission) => permission.key);

export const defaultRolePermissionMap: Record<string, string[]> = {
  super_admin: allPermissionKeys,
  admin: allPermissionKeys.filter((permissionKey) => permissionKey !== 'role_delete'),
  manager: [
    'user_view',
    'role_view',
    'permission_view',
    'vehicle_view',
    'vehicle_create',
    'vehicle_update',
    'vehicle_delete',
    'driver_view',
    'driver_create',
    'driver_update',
    'driver_delete',
    'asset_view',
    'asset_create',
    'asset_update',
    'asset_delete',
    'asset_assign',
    'asset_return',
    'asset_transfer',
    'asset_mark_damaged',
    'asset_mark_lost',
    'trip_view',
    'trip_create',
    'trip_update',
    'trip_start',
    'trip_end',
    'trip_cancel',
    'fuel_view',
    'fuel_create',
    'fuel_update',
    'fuel_submit',
    'fuel_approve',
    'expense_view',
    'expense_create',
    'expense_update',
    'expense_submit',
    'expense_approve',
    'repair_view',
    'repair_create',
    'repair_update',
    'repair_close',
    'maintenance_view',
    'maintenance_create',
    'maintenance_update',
    'maintenance_submit',
    'maintenance_approve',
    'report_view',
    'report_export',
    'settings_view',
    'user_deactivate',
    'vehicle_compliance_view',
    'vehicle_compliance_create',
    'vehicle_compliance_update',
    'vehicle_compliance_delete',
    'vehicle_compliance_verify',
    'vehicle_compliance_renew',
    'document_metadata_view',
    'document_metadata_create',
    'document_metadata_update',
    'document_metadata_delete',
    'document_metadata_verify',
    'documents_view',
    'documents_upload',
    'documents_download',
    'documents_update',
    'documents_delete',
    'documents_verify',
    'documents_archive',
    'compliance_alerts_view',
    'compliance_history_view',
    'alerts_view',
    'alerts_manage',
    'alerts_resolve',
    'report_export',
  ],
  supervisor: [
    'vehicle_view',
    'vehicle_create',
    'vehicle_update',
    'driver_view',
    'driver_create',
    'driver_update',
    'asset_view',
    'asset_create',
    'asset_update',
    'asset_assign',
    'asset_return',
    'asset_transfer',
    'asset_mark_damaged',
    'asset_mark_lost',
    'trip_view',
    'trip_create',
    'trip_update',
    'trip_start',
    'trip_end',
    'trip_cancel',
    'fuel_view',
    'fuel_create',
    'fuel_update',
    'fuel_submit',
    'expense_view',
    'expense_create',
    'expense_update',
    'expense_submit',
    'repair_view',
    'repair_create',
    'repair_update',
    'maintenance_view',
    'maintenance_create',
    'maintenance_update',
    'report_view',
    'vehicle_compliance_view',
    'vehicle_compliance_create',
    'vehicle_compliance_update',
    'document_metadata_view',
    'document_metadata_create',
    'documents_view',
    'documents_upload',
    'documents_download',
    'compliance_history_view',
    'alerts_view',
    'alerts_resolve',
  ],
  driver: ['trip_view', 'trip_start', 'trip_end', 'vehicle_compliance_view', 'compliance_alerts_view', 'alerts_view'],
  assistant_driver: ['trip_view', 'alerts_view'],
  collector: [
    'payments_view',
    'payments_create',
    'trip_billing_view',
    'customers_view',
    'finance_view',
    'report_view',
    'alerts_view',
    'alerts_resolve',
  ],
  mechanic: ['repair_view', 'repair_update', 'repair_close', 'maintenance_view', 'maintenance_update', 'vehicle_compliance_view', 'vehicle_compliance_create', 'vehicle_compliance_update', 'document_metadata_view', 'documents_view', 'documents_upload', 'documents_download', 'compliance_history_view', 'alerts_view', 'alerts_resolve'],
  finance: [
    'finance_view',
    'finance_create',
    'finance_update',
    'finance_delete',
    'finance_approve',
    'finance_transactions_view',
    'finance_transactions_create',
    'finance_transactions_update',
    'finance_transactions_delete',
    'trip_billing_view',
    'trip_billing_create',
    'trip_billing_update',
    'trip_billing_delete',
    'trip_billing_mark_paid',
    'payments_view',
    'payments_create',
    'payments_update',
    'payments_delete',
    'vendors_view',
    'vendors_create',
    'vendors_update',
    'vendors_delete',
    'customers_view',
    'customers_create',
    'customers_update',
    'customers_delete',
    'pnl_view',
    'finance_history_view',
    'documents_view',
    'documents_upload',
    'documents_download',
    'documents_update',
    'documents_archive',
    'fuel_view',
    'fuel_approve',
    'expense_view',
    'expense_approve',
    'report_view',
    'report_export',
    'alerts_view',
    'alerts_resolve',
  ],
  viewer: [
    'vehicle_view',
    'driver_view',
    'asset_view',
    'trip_view',
    'fuel_view',
    'expense_view',
    'repair_view',
    'maintenance_view',
    'report_view',
    'vehicle_compliance_view',
    'compliance_alerts_view',
    'compliance_history_view',
    'document_metadata_view',
    'documents_view',
    'role_view',
    'user_view',
    'permission_view',
    'alerts_view',
  ],
};
