type PermissionDefinition = {
  key: string;
  module: string;
  action: string;
  description: string;
};

type RoleDefinition = {
  name: string;
  key: string;
  description: string;
  isSystem: boolean;
  status: 'ACTIVE' | 'INACTIVE';
};

export const permissionDefinitions: PermissionDefinition[] = [
  { key: 'user_view', module: 'users', action: 'view', description: 'View users' },
  { key: 'user_create', module: 'users', action: 'create', description: 'Create users' },
  { key: 'user_update', module: 'users', action: 'update', description: 'Update users' },
  { key: 'user_delete', module: 'users', action: 'delete', description: 'Delete users' },
  { key: 'user_deactivate', module: 'users', action: 'deactivate', description: 'Deactivate users' },
  { key: 'role_view', module: 'roles', action: 'view', description: 'View roles' },
  { key: 'role_create', module: 'roles', action: 'create', description: 'Create roles' },
  { key: 'role_update', module: 'roles', action: 'update', description: 'Update roles' },
  { key: 'role_delete', module: 'roles', action: 'delete', description: 'Delete roles' },
  { key: 'permission_view', module: 'permissions', action: 'view', description: 'View permissions' },
  { key: 'permission_assign', module: 'permissions', action: 'assign', description: 'Assign permissions' },
  { key: 'vehicle_view', module: 'vehicles', action: 'view', description: 'View vehicles' },
  { key: 'vehicle_create', module: 'vehicles', action: 'create', description: 'Create vehicles' },
  { key: 'vehicle_update', module: 'vehicles', action: 'update', description: 'Update vehicles' },
  { key: 'vehicle_delete', module: 'vehicles', action: 'delete', description: 'Delete vehicles' },
  { key: 'driver_view', module: 'drivers', action: 'view', description: 'View drivers' },
  { key: 'driver_create', module: 'drivers', action: 'create', description: 'Create drivers' },
  { key: 'driver_update', module: 'drivers', action: 'update', description: 'Update drivers' },
  { key: 'driver_delete', module: 'drivers', action: 'delete', description: 'Delete drivers' },
  { key: 'asset_view', module: 'assets', action: 'view', description: 'View assets' },
  { key: 'asset_create', module: 'assets', action: 'create', description: 'Create assets' },
  { key: 'asset_update', module: 'assets', action: 'update', description: 'Update assets' },
  { key: 'asset_delete', module: 'assets', action: 'delete', description: 'Delete assets' },
  { key: 'asset_assign', module: 'assets', action: 'assign', description: 'Assign assets' },
  { key: 'asset_return', module: 'assets', action: 'return', description: 'Return assets' },
  { key: 'asset_transfer', module: 'assets', action: 'transfer', description: 'Transfer assets between holders' },
  { key: 'asset_mark_damaged', module: 'assets', action: 'mark_damaged', description: 'Mark assets as damaged' },
  { key: 'asset_mark_lost', module: 'assets', action: 'mark_lost', description: 'Mark assets as lost' },
  { key: 'trip_view', module: 'trips', action: 'view', description: 'View trips' },
  { key: 'trip_create', module: 'trips', action: 'create', description: 'Create trips' },
  { key: 'trip_update', module: 'trips', action: 'update', description: 'Update trips' },
  { key: 'trip_start', module: 'trips', action: 'start', description: 'Start trips' },
  { key: 'trip_end', module: 'trips', action: 'end', description: 'End trips' },
  { key: 'trip_cancel', module: 'trips', action: 'cancel', description: 'Cancel trips' },
  { key: 'fuel_view', module: 'fuel', action: 'view', description: 'View fuel logs' },
  { key: 'fuel_create', module: 'fuel', action: 'create', description: 'Create fuel logs' },
  { key: 'fuel_update', module: 'fuel', action: 'update', description: 'Update fuel logs' },
  { key: 'fuel_delete', module: 'fuel', action: 'delete', description: 'Delete or cancel fuel logs' },
  { key: 'fuel_submit', module: 'fuel', action: 'submit', description: 'Submit fuel logs' },
  { key: 'fuel_approve', module: 'fuel', action: 'approve', description: 'Approve fuel logs' },
  { key: 'expense_view', module: 'expenses', action: 'view', description: 'View expenses' },
  { key: 'expense_create', module: 'expenses', action: 'create', description: 'Create expenses' },
  { key: 'expense_update', module: 'expenses', action: 'update', description: 'Update expenses' },
  { key: 'expense_delete', module: 'expenses', action: 'delete', description: 'Delete or cancel expenses' },
  { key: 'expense_submit', module: 'expenses', action: 'submit', description: 'Submit expenses' },
  { key: 'expense_approve', module: 'expenses', action: 'approve', description: 'Approve expenses' },
  { key: 'maintenance_view', module: 'maintenance', action: 'view', description: 'View maintenance requests' },
  { key: 'maintenance_create', module: 'maintenance', action: 'create', description: 'Create maintenance requests' },
  { key: 'maintenance_update', module: 'maintenance', action: 'update', description: 'Update maintenance requests' },
  { key: 'maintenance_delete', module: 'maintenance', action: 'delete', description: 'Delete maintenance requests' },
  { key: 'maintenance_submit', module: 'maintenance', action: 'submit', description: 'Submit maintenance requests' },
  { key: 'maintenance_approve', module: 'maintenance', action: 'approve', description: 'Approve maintenance requests' },
  { key: 'maintenance_assign', module: 'maintenance', action: 'assign', description: 'Assign maintenance to mechanic' },
  { key: 'maintenance_complete', module: 'maintenance', action: 'complete', description: 'Complete maintenance requests' },
  { key: 'repair_view', module: 'repairs', action: 'view', description: 'View repairs' },
  { key: 'repair_create', module: 'repairs', action: 'create', description: 'Create repairs' },
  { key: 'repair_update', module: 'repairs', action: 'update', description: 'Update repairs' },
  { key: 'repair_delete', module: 'repairs', action: 'delete', description: 'Delete repairs' },
  { key: 'repair_assign', module: 'repairs', action: 'assign', description: 'Assign repairs to mechanic' },
  { key: 'repair_complete', module: 'repairs', action: 'complete', description: 'Complete repairs' },
  { key: 'finance_view', module: 'finance', action: 'view', description: 'View finance' },
  { key: 'finance_approve', module: 'finance', action: 'approve', description: 'Approve finance records' },
  { key: 'report_view', module: 'reports', action: 'view', description: 'View reports' },
  { key: 'report_export', module: 'reports', action: 'export', description: 'Export reports' },
  { key: 'settings_view', module: 'settings', action: 'view', description: 'View settings' },
  { key: 'settings_update', module: 'settings', action: 'update', description: 'Update settings' },
];

export const roleDefinitions: RoleDefinition[] = [
  { name: 'Super Admin', key: 'super_admin', description: 'Full platform control', isSystem: true, status: 'ACTIVE' },
  { name: 'Admin', key: 'admin', description: 'Company administration', isSystem: true, status: 'ACTIVE' },
  { name: 'Manager', key: 'manager', description: 'Operations manager', isSystem: true, status: 'ACTIVE' },
  { name: 'Supervisor', key: 'supervisor', description: 'Field supervisor', isSystem: true, status: 'ACTIVE' },
  { name: 'Driver', key: 'driver', description: 'Assigned driver', isSystem: true, status: 'ACTIVE' },
  { name: 'Assistant Driver', key: 'assistant_driver', description: 'Assistant driver', isSystem: true, status: 'ACTIVE' },
  { name: 'Collector', key: 'collector', description: 'Collection operator', isSystem: true, status: 'ACTIVE' },
  { name: 'Mechanic', key: 'mechanic', description: 'Repair operator', isSystem: true, status: 'ACTIVE' },
  { name: 'Finance', key: 'finance', description: 'Finance approver', isSystem: true, status: 'ACTIVE' },
  { name: 'Viewer', key: 'viewer', description: 'Read-only operator', isSystem: true, status: 'ACTIVE' },
];

export const criticalSuperAdminPermissionKeys = [
  'role_view',
  'role_update',
  'permission_view',
  'permission_assign',
  'user_view',
  'user_create',
  'user_update',
];

export const criticalRoleManagementPermissionKeys = [
  'role_view',
  'role_update',
  'permission_view',
  'permission_assign',
];

const allPermissionKeys = permissionDefinitions.map((permission) => permission.key);
const viewOnlyPermissionKeys = permissionDefinitions
  .filter((permission) => permission.action === 'view')
  .map((permission) => permission.key);

export const defaultRolePermissionMap: Record<string, string[]> = {
  super_admin: allPermissionKeys,
  admin: allPermissionKeys.filter((permissionKey) => permissionKey !== 'role_delete'),
  manager: [
    'user_view',
    'role_view',
    'permission_view',
    'vehicle_view',
    'vehicle_create',
    'vehicle_update',
    'vehicle_delete',
    'driver_view',
    'driver_create',
    'driver_update',
    'driver_delete',
    'asset_view',
    'asset_create',
    'asset_update',
    'asset_delete',
    'asset_assign',
    'asset_return',
    'asset_transfer',
    'asset_mark_damaged',
    'asset_mark_lost',
    'trip_view',
    'trip_create',
    'trip_update',
    'trip_start',
    'trip_end',
    'trip_cancel',
    'fuel_view',
    'fuel_create',
    'fuel_update',
    'fuel_submit',
    'fuel_approve',
    'expense_view',
    'expense_create',
    'expense_update',
    'expense_submit',
    'expense_approve',
    'repair_view',
    'repair_create',
    'repair_update',
    'repair_assign',
    'repair_complete',
    'maintenance_view',
    'maintenance_create',
    'maintenance_update',
    'maintenance_submit',
    'maintenance_approve',
    'maintenance_assign',
    'maintenance_complete',
    'finance_view',
    'report_view',
    'report_export',
    'settings_view',
    'user_deactivate',
  ],
  supervisor: [
    'vehicle_view',
    'vehicle_create',
    'vehicle_update',
    'driver_view',
    'driver_create',
    'driver_update',
    'asset_view',
    'asset_create',
    'asset_update',
    'asset_assign',
    'asset_return',
    'asset_transfer',
    'asset_mark_damaged',
    'asset_mark_lost',
    'trip_view',
    'trip_create',
    'trip_update',
    'trip_start',
    'trip_end',
    'trip_cancel',
    'fuel_view',
    'fuel_create',
    'fuel_update',
    'fuel_submit',
    'expense_view',
    'expense_create',
    'expense_update',
    'expense_submit',
    'repair_view',
    'repair_create',
    'repair_update',
    'maintenance_view',
    'maintenance_create',
    'maintenance_update',
    'maintenance_submit',
    'report_view',
  ],
  driver: ['trip_view', 'trip_start', 'trip_end'],
  assistant_driver: ['trip_view'],
  collector: ['finance_view', 'report_view'],
  mechanic: ['repair_view', 'repair_update', 'repair_assign', 'repair_complete', 'maintenance_view'],
  finance: ['finance_view', 'finance_approve', 'fuel_view', 'fuel_approve', 'expense_view', 'expense_approve', 'report_view', 'report_export'],
  viewer: viewOnlyPermissionKeys,
};
